#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

CONFIG_PATH="${CARTOLENSIA_LOCAL_FULL_BUILD_CONFIG:-config/local-full-build.env}"
if [ -f "${CONFIG_PATH}" ]; then
  # shellcheck disable=SC1090
  set -a
  . "${CONFIG_PATH}"
  set +a
fi

export CARTOLENSIA_RELEASE_INCLUDE_TOOLS="${CARTOLENSIA_RELEASE_INCLUDE_TOOLS:-1}"
export CARTOLENSIA_RELEASE_INCLUDE_POSTGRES="${CARTOLENSIA_RELEASE_INCLUDE_POSTGRES:-1}"
export CARTOLENSIA_RELEASE_INCLUDE_PYTHON_RUNTIME="${CARTOLENSIA_RELEASE_INCLUDE_PYTHON_RUNTIME:-1}"
export CARTOLENSIA_RELEASE_INCLUDE_MODELS="${CARTOLENSIA_RELEASE_INCLUDE_MODELS:-1}"
export CARTOLENSIA_RELEASE_INCLUDE_OFFLINE_MAPS="${CARTOLENSIA_RELEASE_INCLUDE_OFFLINE_MAPS:-1}"
export CARTOLENSIA_RELEASE_AI_FLAVOR="${CARTOLENSIA_RELEASE_AI_FLAVOR:-cpu}"

exec bash scripts/release/build-linux.sh
