#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

export CARTOLENSIA_DIST_VERSION="${CARTOLENSIA_RELEASE_VERSION:-${CARTOLENSIA_DIST_VERSION:-$(git describe --tags --always --dirty 2>/dev/null || date -u +%Y%m%d%H%M%S)}}"
export CARTOLENSIA_DIST_TARGET="${CARTOLENSIA_RELEASE_TARGET:-${CARTOLENSIA_DIST_TARGET:-linux-x86_64}}"
export CARTOLENSIA_DIST_INCLUDE_TOOLS="${CARTOLENSIA_RELEASE_INCLUDE_TOOLS:-${CARTOLENSIA_DIST_INCLUDE_TOOLS:-1}}"
export CARTOLENSIA_DIST_INCLUDE_POSTGRES="${CARTOLENSIA_RELEASE_INCLUDE_POSTGRES:-${CARTOLENSIA_DIST_INCLUDE_POSTGRES:-1}}"
export CARTOLENSIA_DIST_INCLUDE_MODELS="${CARTOLENSIA_RELEASE_INCLUDE_MODELS:-${CARTOLENSIA_DIST_INCLUDE_MODELS:-0}}"
export CARTOLENSIA_DIST_INCLUDE_PYTHON_RUNTIME="${CARTOLENSIA_RELEASE_INCLUDE_PYTHON_RUNTIME:-${CARTOLENSIA_DIST_INCLUDE_PYTHON_RUNTIME:-1}}"
export CARTOLENSIA_DIST_INCLUDE_OFFLINE_MAPS="${CARTOLENSIA_RELEASE_INCLUDE_OFFLINE_MAPS:-${CARTOLENSIA_DIST_INCLUDE_OFFLINE_MAPS:-0}}"
export CARTOLENSIA_DIST_AI_FLAVOR="${CARTOLENSIA_RELEASE_AI_FLAVOR:-${CARTOLENSIA_DIST_AI_FLAVOR:-runtime}}"
export CARTOLENSIA_DIST_DIR="${CARTOLENSIA_RELEASE_DIST_DIR:-${CARTOLENSIA_DIST_DIR:-${ROOT_DIR}/dist}}"

if [ "${CARTOLENSIA_DIST_INCLUDE_PYTHON_RUNTIME}" = "0" ]; then
  export CARTOLENSIA_DIST_AI_FLAVOR=none
fi

exec bash scripts/dist/build-offline-linux.sh
